name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Hello ${{ github.actor }},

          Thank you for being part of the Anchore community!

          An Anchorite will look at your issue soon. We also have great [documentation](https://docs.next-linux.systems/current/), including [FAQs](https://docs.next-linux.systems/current/docs/faq/) and [release notes](https://docs.next-linux.systems/current/docs/releasenotes/).

          You can also find our [contribution guidelines here](https://github.com/nextlinux/engine-db-preload/blob/master/CONTRIBUTING.rst). Thank you again!
